name: Autobuild TGUI

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    name: TGUI Rebuild
    runs-on: ubuntu-latest
    steps:
      #- name: Check Comment
      #  uses: khan/pull-request-comment-trigger@bb03972cc9f423111f3b5a23fcc9fd32741acabb
      #  id: check
      #  with:
      #    trigger: '?rebuild'
      #    reaction: rocket
      #  env:
      #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # make sure this is correct depending on branch protection setup
      - name: Checkout
        #if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Setup Node
        #if: steps.check.outputs.triggered == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '>=12.13'
      - name: Build TGUI
        #if: steps.check.outputs.triggered == 'true'
        run: bin/tgui
        working-directory: ./tgui
      - name: Commit and Push Build
        #if: steps.check.outputs.triggered == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "TGUI Rebuild"
          git commit -m "TGUI Rebuild [ci skip]" -a || true
          git push
